### ISSUE TITLE
In main.py, targets[:,0] is an array containing -100's

### ISSUE THREAD

**Issue by therealanshuman** [loicland/superpoint_graph#108]
While trying to execute `main.py`, I observed the fact that the first column of the `targets` array has a list of -100 value as its contents in the method `train`. I am getting an error `RuntimeError: the given numpy array has zero-sized dimensions. Zero-sized dimensions are not supported in PyTorch` due to the fact that the `filter_valid` method in `main.py` is returning empty arrays. What might be the problem here? Why are all the target values -100?

I have 2 labels for the custom data that I am using. Should the label values be 0 and 1 or 1 and 2? Currently, the label values are 0 and 1 and `n_labels = 2` everywhere, although I have put 0 as unlabeled, and 1 and 2 as my labels in the `get_color_from_label` method in `provider.py`. I don't have any unlabeled points in my dataset. Also, should the label array be one-hot encoded or just a list of values while returning from `read_custom_format` in `provider.py`? Currently, I'm just returning a list of labels.

**Comment by loicland** [comment]
Hi,

- as mentioned in the comment line 70 of `/learning/spg.py`, the value -100 is sued for superpoints which contains only unannotated data.

- if filter_valid returns this error it means that none of the superpoints in the selected subgraph has any annotation. This is due to the next point.

- 0 is resevred for unannotated data. your classes should be 1 and 2. Note that the network will return 0 and 1 at inference, shifting the labels by one (since it never predicts "unannotated".
See the following issues: 
https://github.com/loicland/superpoint_graph/issues/94
https://github.com/loicland/superpoint_graph/issues/63

- `labels` should be an array of uint8 containing the class index.

Let me know if this fixes your problems.
