### ISSUE TITLE
Subset (neighborhood) selection of (permuted) superpoint graph

### ISSUE THREAD

**Issue by hagianga21** [loicland/superpoint_graph#113]
Hi, in spg.py, in dataloader function. First, you used permute_vertices then use random_neighborhoods and you say "after hardcutoff, neighborhoods may be broken". Finally run k_big_enough function. Why don't you use random_neighborhoods after k_big_enough function? Because after running  k_big_enough function, some node is removed and also edges. As a result, neighborhoods may be broken. Thank you so much. I have some confusing in the logic at this stage.

**Comment by loicland** [comment]
Hi,

Both `random_neighborhoods` and `k_big_enough`'s aim is to decrease the size of the SPG so it fits in memory, and also adding diversity in the topology of the SPG seen at training time. We run `k_big_enough` last because we want the SPGs being of controlled size so that the batch size fits in memory while embedding as many spuerpoints as possible.

However, if you can think of another way of augmenting the SPG go for it, ours is definitively an heuristic.
