### ISSUE TITLE
Classification workflow

### ISSUE THREAD

**Issue by bastlen** [loicland/superpoint_graph#115]
Hello,
first - thank you for publishing your work.
AS described in PointNet there is a classification workflow. Is there a way to classify objects with this approach?
Best regards
Sebastian

**Comment by loicland** [comment]
Hi,

If I understand correctly you are asking of you can use SPG for object classification instead of semantic segmentation?

I am not certain SPG would be appropriate. Are your objects so huge and complicated that you can't use PointNet?

You could feed the superpoint embeddings directly to a pointnet. But I am not certain this is a good way to proceed. SPG works specifically when your point clouds are very large. Is this your case?
