### ISSUE TITLE
Questions about folds and resuming training

### ISSUE THREAD

**Issue by tfwittwer** [loicland/superpoint_graph#245]
Hi,
I'm new to the world of ANNs, so please forgive me if these are stupid questions. 

1. For some datasets, you use multiple folds, while for others you don't. What's the reasoning behind this? If I understand correctly, multiple folds mean that you train multiple models on subsets of the training data, correct? How would you combine the results of multiple folds?
2. How would one resume training an existing model with new data? Increase the number of maximum iterations, then resume training with the new data replacing the initial data?

**Comment by loicland** [comment]
1- we perform 6-fold cross validation on s3dis because there is a natural fold partition. For each fold, we train a model and evaluate the 5 other folds and evaluate it on the fold in question. The prediction are aggregated over the 6 fold, covering the entire dataset.

Cross validation is a good practice for evaluating an algorithm.  If your goal is to have the best possible model on indoor data, use all 6bfolds to train.

2- see our guides for 3dis and sema3d. You set --n_epoch to -1 and --resume to 1

**Comment by loicland** [comment]
Hi!

We are releasing a new version of SuperPoint Graph called SuperPoint Transformer (SPT).
It is better in any way:

| ✨ SPT in numbers ✨ |
| :---: |
| 📊 **SOTA results:** 76.0 mIoU S3DIS 6-Fold, 63.5 mIoU on KITTI-360 Val, 79.6 mIoU on DALES  |
| 🦋 **212k parameters only!** | 
| ⚡ Trains on S3DIS in **3h on 1 GPU**| 
| ⚡ **Preprocessing is x7 faster than SPG!** |
| 🚀  **Easy install** (no more boost!)|

If you are interested in lightweight, high-performance 3D deep learning, you should check it out. In the meantime, we will finally retire SPG and stop maintaining this repo.
