### ISSUE TITLE
S3DIS model Inference on other dataset

### ISSUE THREAD

**Issue by nicolas-chaulet** [loicland/superpoint_graph#66]
Hi Loic,
Thanks a lot for providing such a great project. I would like to use an SPG model trained on the S3DIS dataset to segment some indoor scenes of my own. The point clouds we collect do not have colour information and I trained a new SPG model on the S3DIS dataset without colour information with no problem on the cross validation split number 1. I get some good results on train and test sets which is good. 

Things get a little more troublesome when I use this model to segment my own point clouds, it performs not well at all by mi classifying a lot more points than expected inside the room, see some results below:
![screen shot 2018-11-19 at 4 37 41 pm](https://user-images.githubusercontent.com/3178237/48721269-753bf000-ec19-11e8-9549-f9a0946c5223.png)

It misses the table, chairs and sofa when they definitely look similar to the ones in the S3DIS dataset. I know it's a big ask but I was wondering if you had an idea of what could have gone wrong there?
The model, training logs and various visualisation output can be found there:
https://drive.google.com/drive/folders/1M_e3XW_72NfqxEbnQFCo7Ubd2Ch8XoMG?usp=sharing
 
Thanks in advance,
Nicolas

**Comment by loicland** [comment]
Hi,

I don't have time this week for a deep dive in your data this week, but will probably next week.

In the meantime, the dataset seems indeed quite close to S3DIS and should perform better indeed. 
Here are some leads for what the problem might have been:
- in S3DIS the point cloud is voxelized with 1cm cubes. In our preprocessing, we subsample it to 3cm so that the clouds are lighter and with less geometric/radiometric noise. Your density seems a bit irregular, have you tried the pruning step as in line 124 of `partition/partition.py`? Different density could throw off the PointNets unit as well as the partition step which will output differently shaped superpoints.
- In S3DIS the parameters XYZ are normalized position in the room. In your preprocessing function (similar to `learning/s3dis_dataset.py`, the function that ouputs the parsed files), make sure that your computation of XYZ are similar to line 88. Alternatively, just remove XYZ and only use xyzelpsv features for the pointnets, or even just xyze.

let me know how this go, I will have some time soon to help if you're still stuck.

**Comment by nicolas-chaulet** [comment]
Hi Loic,
Thanks a lot for you answer, there is no rush and I really appreciate your interest and support. Yes, I am doing the two things you suggest, I just double checked and it looks just fine to me. One thing is that the surfaces in our dataset are a lot less clean than in the S3DIS dataset. Walls have thickness, same for table top for example. I will try to smooth it out as a preprocessing step and see if that helps.

**Comment by loicland** [comment]
In which case I would:
- retrain without the lpsv values which will be greatly affected by the geometric noise
- increase the jitter on S3DIS to make it look more like yours (line 244 of `learning/spg.py`). Careful with this parameter, if too high the pointNets won't learn anything useful.

**Comment by nicolas-chaulet** [comment]
Hi Loic,
Quick update on this case. I am quite certain now that the issue is related to the way I prepare the data and specifically to the scaling that is applied to the edge features (line 37 in `learning/s3dis_dataset.py`). I did not pay attention to this too much but now it is obvious that we need to scale the edge features using the same scaling factors as the one used during training. I still need to do some more testing but I really think this is the source of my troubles.

**Comment by loicland** [comment]
Glad to hear it.

Note as well that the rooms in S3DIS are aligned with either the x or y axis. Try to do the same for your dataset, especially if you use XYZ as point features.

**Comment by nicolas-chaulet** [comment]
I was actually just writing to you. It was definitely the sedge feature normalisation that created the issue. It even does ok on noisy data.
![screen shot 2018-11-29 at 1 03 18 pm](https://user-images.githubusercontent.com/3178237/49223750-98179280-f3d7-11e8-8fd8-ec618ce6e43c.png)

Yes, I saw that the dataset is aligned. I actually would like to get rid of this concept of rooms, in my experience it's actually complicated to get this kind of information in the first place from field data.
