### ISSUE TITLE
is it possible change from PointNet to PointNet++?

### ISSUE THREAD

**Issue by cbyzju** [loicland/superpoint_graph#78]
Recently, I studied your paper and code, and I wonder whether you try PointNet++ as the pointcloud embedding layer, and if we do so, is it possible that the accuracy and segmentation performance might be better?

**Comment by loicland** [comment]
Hi,

You can indeed replace the PointNet by any point cloud embedder you like. However, I don't think Pointnet++ would be the best replacement since the superpoints are by design simple in shape, and Pointnet++'s hierarchical feature extraction would be a bit overkill. PointCNN might be a better idea.

Lastly, keep in mind that most of the precision comes from the graph convolutions (see our ablation study), so improving the embedders might not have a huge effect on the overall precision.
