### ISSUE TITLE
space structure is much more important than other feature?

### ISSUE THREAD

**Issue by cbyzju** [loicland/superpoint_graph#91]
Hi Loic,
 These days, I try to segment traffic signs (turn left, turn right or go straight)and lane line from the ground point cloud, Considering the space structures of these objects are very similar, I use color and intensity features to help the segmentation, but the result is very bad, the trained model can not tell one object from others, could you give some suggestions?

**Comment by loicland** [comment]
Hi,

Just so I understand, the partition step fails or the segmentation? Can you post an image of faulty segmentation?

If you think that the partition fails because not enough weight are given to radio metric information, you can increase their relative importance in partition.py (with lines such as `geof[:,3] = 2. * geof[:, 3]`).

Alternatively, if you have instance ground truth, we will release soonish a fully supervised method for the partition step, this might help.
